apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - uniformdata-deployment.yaml
  - uniformdata-svc.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: uniformdata
    path: prod_patches/uniformdata-prod.yaml