apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - uniformdata-deployment.yaml
  - uniformdata-svc.yaml
  
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: uniformdata-svc
    path: local_patches/uniformdata-svc-dev.yaml